- name: Download Packer
  get_url:
    url: "https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip"
    dest: "/tmp/packer.zip"

- name: Extract Packer
  unarchive:
    src: /tmp/packer.zip
    dest: /usr/local
    remote_src: yes