- name: Download Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip"
    dest: "/tmp/terraform.zip"

- name: Extract Terraform
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local
    remote_src: yes

- name: Pull sources from the repository.
  git: repo={{ item }} dest={{ terraform_project_root }} version={{ terraform_branch }} accept_hostkey=yes
  become_user: ubuntu
  with_items: "{{ terraform_repos }}"
