- name: "Stop Teamcity Server"
  shell: sudo service teamcity-server stop

# - copy:
#     src: "files/TeamCityBackup.zip"
#     dest: "/opt/TeamCity/.BuildServer/import/TeamCityBackup.zip"
#     owner: teamcity
#     group: teamcity
#     mode: 0644

- name: Drop Database
  shell: dropdb sfteamcity -U teamcity -W {{ teamcity_db_password }}

- name: Create Database
  shell: createdb sfteamcity -U teamcity -W {{ teamcity_db_password }}

# - name: Restore Backup
#   shell: /opt/TeamCity/bin/maintainDB.sh restore -A /opt/TeamCity/ -F /home/ubuntu/TeamCityBackup.zip  -T /opt/TeamCity/.BuildServer/config/database.properties

# - name: "Start Teamcity Server"
#   shell: sudo service teamcity-server start